services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: cnpj-postgres:latest
    container_name: cnpj-postgres
    restart: unless-stopped
    environment:
        POSTGRES_DB: cnpj_db
        POSTGRES_USER: cnpj
        POSTGRES_PASSWORD: cnpj123
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - cnpj_postgres_logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cnpj -d cnpj_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cnpj_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cnpj-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config/pgadmin-servers.json:/pgadmin4/servers.json:ro
      - ./config/pgadmin-pgpass:/tmp/pgpassfile:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cnpj_network

volumes:
  pgadmin_data:
    driver: local
  cnpj_postgres_logs:
    driver: local

networks:
  cnpj_network:
    driver: bridge
