base_url: 'https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj'

# Incoming CSV Settings
csv_sep: ';'
csv_dec: ','
csv_quote: '"'
csv_enc: 'latin1'

# Database structure definitions for each table
database_structure:
  motivos:
    codigo_motivo:
      type: "TEXT"
      index: true
    descricao_motivo:
      type: "TEXT"

  municipios:
    codigo_municipio:
      type: "TEXT"
      index: true
    nome_municipio:
      type: "TEXT"

  natureza:
    codigo_natureza_juridica:
      type: "TEXT"
      index: true
    descricao_natureza_juridica:
      type: "TEXT"

  qualificacoes:
    codigo_qualificacao:
      type: "TEXT"
      index: true
    descricao_qualificacao:
      type: "TEXT"

  paises:
    codigo_pais:
      type: "TEXT"
      index: true
    nome_pais:
      type: "TEXT"

  empresas:
    cnpj_basico:
      type: "TEXT"
      index: true
    razao_social:
      type: "TEXT"
      index: true
    natureza_juridica:
      type: "TEXT"
      index: true
    qualificacao_do_responsavel:
      type: "TEXT"
    capital_social:
      type: "TEXT"
    porte_da_empresa:
      type: "TEXT"
    ente_federativo_responsavel:
      type: "TEXT"

  estabelecimentos:
    cnpj_basico:
      type: "TEXT"
      index: true
    cnpj_ordem:
      type: "TEXT"
    cnpj_dv:
      type: "TEXT"
    identificador_matriz_filial:
      type: "TEXT"
    nome_fantasia:
      type: "TEXT"
    situacao_cadastral:
      type: "TEXT"
      index: true
    data_situacao_cadastral:
      type: "TEXT"
    motivo_situacao_cadastral:
      type: "TEXT"
    nome_da_cidade_no_exterior:
      type: "TEXT"
    pais:
      type: "TEXT"
    data_de_inicio_da_atividade:
      type: "TEXT"
    cnae_fiscal_principal:
      type: "TEXT"
      index: true
    cnae_fiscal_secundaria:
      type: "TEXT"
    tipo_de_logradouro:
      type: "TEXT"
    logradouro:
      type: "TEXT"
    numero:
      type: "TEXT"
    complemento:
      type: "TEXT"
    bairro:
      type: "TEXT"
    cep:
      type: "TEXT"
    uf:
      type: "TEXT"
      index: true
    municipio:
      type: "TEXT"
      index: true
    ddd1:
      type: "TEXT"
    telefone1:
      type: "TEXT"
    ddd2:
      type: "TEXT"
    telefone2:
      type: "TEXT"
    ddd_do_fax:
      type: "TEXT"
    fax:
      type: "TEXT"
    correio_eletronico:
      type: "TEXT"
    situacao_especial:
      type: "TEXT"
    data_da_situacao_especial:
      type: "TEXT"

  socios:
    cnpj_basico:
      type: "TEXT"
      index: true
    identificador_de_socio:
      type: "TEXT"
    nome_do_socio:
      type: "TEXT"
    cnpj_ou_cpf_do_socio:
      type: "TEXT"
    qualificacao_do_socio:
      type: "TEXT"
    data_de_entrada_sociedade:
      type: "TEXT"
    pais:
      type: "TEXT"
    representante_legal:
      type: "TEXT"
    nome_do_representante:
      type: "TEXT"
    qualificacao_do_representante_legal:
      type: "TEXT"
    faixa_etaria:
      type: "TEXT"

  simples:
    cnpj_basico:
      type: "TEXT"
      index: true
    opcao_pelo_simples:
      type: "TEXT"
    data_opcao_simples:
      type: "TEXT"
    data_exclusao_simples:
      type: "TEXT"
    opcao_pelo_mei:
      type: "TEXT"
    data_opcao_mei:
      type: "TEXT"
    data_exclusao_mei:
      type: "TEXT"

  cnaes:
    cnpj_basico:
      type: "TEXT"
      index: true
    cnae_fiscal_secundaria:
      type: "TEXT"
      index: true