base_url: 'https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj'

# Incoming CSV Settings
csv_sep: ';'
csv_dec: ','
csv_quote: '"'
csv_enc: 'latin1'

# Export format: Choose between 'csv', 'parquet', 'json', or 'feather'
export_format: 'parquet'

# Data type definitions for each table
dtypes:
  empresas:
    cnpj_basico: "string"
    razao_social: "string"
    natureza_juridica: "string"
    qualificacao_do_responsavel: "string"
    capital_social: "string"
    porte_da_empresa: "string"
    ente_federativo_responsavel: "string"

  estabelecimentos:
    cnpj_basico: "string"
    cnpj_ordem: "string"
    cnpj_dv: "string"
    identificador_matriz_filial: "string"
    nome_fantasia: "string"
    situacao_cadastral: "string"
    data_situacao_cadastral: "string"
    motivo_situacao_cadastral: "string"
    nome_da_cidade_no_exterior: "string"
    pais: "string"
    data_de_inicio_da_atividade: "string"
    cnae_fiscal_principal: "string"
    cnae_fiscal_secundaria: "string"
    tipo_de_logradouro: "string"
    logradouro: "string"
    numero: "string"
    complemento: "string"
    bairro: "string"
    cep: "string"
    uf: "string"
    municipio: "string"
    ddd1: "string"
    telefone1: "string"
    ddd2: "string"
    telefone2: "string"
    ddd_do_fax: "string"
    fax: "string"
    correio_eletronico: "string"
    situacao_especial: "string"
    data_da_situacao_especial: "string"

  socios:
    cnpj_basico: "string"
    identificador_de_socio: "string"
    nome_do_socio: "string"
    cnpj_ou_cpf_do_socio: "string"
    qualificacao_do_socio: "string"
    data_de_entrada_sociedade: "string"
    pais: "string"
    representante_legal: "string"
    nome_do_representante: "string"
    qualificacao_do_representante_legal: "string"
    faixa_etaria: "string"

  cnaes:
    cnpj_basico: "string"
    cnae_fiscal_secundaria: "string"

  motivos:
    codigo_motivo: "string"
    descricao_motivo: "string"

  municipios:
    codigo_municipio: "string"
    nome_municipio: "string"

  natureza:
    codigo_natureza_juridica: "string"
    descricao_natureza_juridica: "string"

  qualificacoes:
    codigo_qualificacao: "string"
    descricao_qualificacao: "string"

  paises:
    codigo_pais: "string"
    nome_pais: "string"

  simples:
    cnpj_basico: "string"
    opcao_pelo_simples: "string"
    data_opcao_simples: "string"
    data_exclusao_simples: "string"
    opcao_pelo_mei: "string"
    data_opcao_mei: "string"
    data_exclusao_mei: "string"